In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report
)


In [4]:
from sklearn.datasets import load_iris

iris = load_iris()
X_iris = iris.data
y_iris = iris.target
iris_features = iris.feature_names
iris_targets = iris.target_names

iris_df = pd.DataFrame(X_iris, columns=iris_features)
iris_df["species"] = [iris_targets[i] for i in y_iris]

print(f"Samples: {X_iris.shape[0]}, Features: {X_iris.shape[1]}")
print(f"Classes: {list(iris_targets)}")
iris_df.head()


Samples: 150, Features: 4
Classes: [np.str_('setosa'), np.str_('versicolor'), np.str_('virginica')]


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [5]:
print("Class distribution:")
print(iris_df["species"].value_counts())

iris_df.describe()


Class distribution:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [6]:
Xi_train, Xi_test, yi_train, yi_test = train_test_split(
    X_iris, y_iris, test_size=0.2, random_state=42, stratify=y_iris
)
print(f"Training samples: {Xi_train.shape[0]}")
print(f"Testing samples:  {Xi_test.shape[0]}")


Training samples: 120
Testing samples:  30


In [7]:
iris_log_model = LogisticRegression(max_iter=200)
iris_log_model.fit(Xi_train, yi_train)

yi_pred_log = iris_log_model.predict(Xi_test)


In [8]:
accuracy = accuracy_score(yi_test, yi_pred_log)

precision = precision_score(yi_test, yi_pred_log, average='macro')
recall = recall_score(yi_test, yi_pred_log, average='macro')
f1 = f1_score(yi_test, yi_pred_log, average='macro')

print(f"Accuracy:  {accuracy:.4f}  -> overall fraction of correct predictions")
print(f"Precision: {precision:.4f}  -> of predicted positives, how many were correct")
print(f"Recall:    {recall:.4f}  -> of actual positives, how many were found")
print(f"F1-Score:  {f1:.4f}  -> balance between precision and recall")

Accuracy:  0.9667  -> overall fraction of correct predictions
Precision: 0.9697  -> of predicted positives, how many were correct
Recall:    0.9667  -> of actual positives, how many were found
F1-Score:  0.9666  -> balance between precision and recall


In [10]:
print("Confusion Matrix (rows=actual, cols=predicted):")
cm = confusion_matrix(yi_test, yi_pred_log)
print(cm)


Confusion Matrix (rows=actual, cols=predicted):
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [11]:
print(classification_report(yi_test, yi_pred_log, target_names=iris_targets))


              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [12]:
sample_idx = np.random.choice(len(Xi_test), 10, replace=False)
sample_df = pd.DataFrame({
    "Actual": [iris_targets[yi_test[i]] for i in sample_idx],
    "Predicted": [iris_targets[yi_pred_log[i]] for i in sample_idx],
})
sample_df["Correct?"] = np.where(sample_df["Actual"] == sample_df["Predicted"], "✓", "✗")
sample_df


,Actual,Predicted,Correct?
0,setosa,setosa,✓
1,setosa,setosa,✓
2,virginica,virginica,✓
3,versicolor,versicolor,✓
4,virginica,virginica,✓
5,versicolor,versicolor,✓
6,virginica,virginica,✓
7,virginica,virginica,✓
8,virginica,virginica,✓
9,setosa,setosa,✓


In [ ]:
iris_tree_model = DecisionTreeClassifier(random_state=42)
iris_tree_model.fit(Xi_train, yi_train)

yi_pred_tree = iris_tree_model.predict(Xi_test)

def evaluate_multiclass(model_name, y_true, y_pred, target_names):
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='macro')
    recall = recall_score(y_true, y_pred, average='macro')
    f1 = f1_score(y_true, y_pred, average='macro')
    cm = confusion_matrix(y_true, y_pred)
    
    print(f"\n{model_name}:")
    print(f"Accuracy:  {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-Score:  {f1:.4f}")
    print("\nConfusion Matrix:")
    print(cm)
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=target_names))
    
    return accuracy, precision, recall, f1, cm


NameError: name 'evaluate_multiclass' is not defined